### PR TITLE
Allow this to work in Laravel 4.2 on PHP 7

### PR DESCRIPTION
**Pull request by JayBizzle**
This will allow this package to work correctly on PHP 7.

Ideally, `Exception` would be changed to `Throwable`, but that wouldn't be backwards compatible, and as this package hasn't been actively developed for a while, I thought this quick fix would be the best solution.

Thanks

### CODE REVIEW

**Comment by anlutro** [comment]
Hey, thanks. I'm going to do a bit of work to make the tests work on PHP7 before merging this in.

**Comment by anlutro** [comment]
Hey, could you rebase your patch-1 branch against this repository's master branch?

```
git remote add upstream https://github.com/anlutro/laravel-4-smart-errors
git update
git rebase upstream/master
git push -f
```

**Comment by JayBizzle** [comment]
No worries, will try and sort that this evening or tomorrow. Thanks

**Comment by JayBizzle** [comment]
Okay, rebase done and tests now all green 👍

**Pull request merged**
